// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetUrl provides a mock function with given fields: ctx, shortCode
func (_m *Repository) GetUrl(ctx context.Context, shortCode string) (string, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetUrl")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreURLIfNotExists provides a mock function with given fields: ctx, code, url, exp
func (_m *Repository) StoreURLIfNotExists(ctx context.Context, code string, url string, exp int) (bool, error) {
	ret := _m.Called(ctx, code, url, exp)

	if len(ret) == 0 {
		panic("no return value specified for StoreURLIfNotExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) (bool, error)); ok {
		return rf(ctx, code, url, exp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) bool); ok {
		r0 = rf(ctx, code, url, exp)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = rf(ctx, code, url, exp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreUrl provides a mock function with given fields: ctx, shortCode, originalUrl
func (_m *Repository) StoreUrl(ctx context.Context, shortCode string, originalUrl string) error {
	ret := _m.Called(ctx, shortCode, originalUrl)

	if len(ret) == 0 {
		panic("no return value specified for StoreUrl")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, shortCode, originalUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
