// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	service "github.com/HOangAG2207/GoBe-K03/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// HealthCheck is an autogenerated mock type for the HealthCheck type
type HealthCheck struct {
	mock.Mock
}

func (_m *HealthCheck) EXPECT() {
	panic("unimplemented")
}

// CheckHealth provides a mock function with no fields
func (_m *HealthCheck) CheckHealth() service.HealthCheckResponse {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 service.HealthCheckResponse
	if rf, ok := ret.Get(0).(func() service.HealthCheckResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(service.HealthCheckResponse)
	}

	return r0
}

// NewHealthCheck creates a new instance of HealthCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthCheck {
	mock := &HealthCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
